// CLI Pulse Helper Uninstaller — minimal Swift app.
//
// Triggered from the MAS app's "Uninstall Companion CLI" button via
// NSWorkspace.shared.open(uninstallerAppURL). Runs as a fully-privileged
// (non-sandboxed) Developer ID notarized .app so it can:
//   1. launchctl bootout the helper agent
//   2. rm the LaunchAgent plist
//   3. Trampoline-self-delete: write a small shell script to /tmp that
//      sleeps 1s, then rm -rf's the helper install directory (including
//      this .app inside it) and removes itself. nohup the script
//      detached, then quit so the script can finish cleanly without
//      racing against an unkillable process.
//
// See PROJECT_PLAN_v1.16_phase4e_helper_production.md §1.10 for the
// pattern reference (Little Snitch / 1Password use the same approach).

import Cocoa
import Foundation

let label = "yyh.cli-pulse.helper"
let helperDir = ("~/Library/CLI-Pulse-Helper" as NSString).expandingTildeInPath
let plistPath = ("~/Library/LaunchAgents/yyh.cli-pulse.helper.plist" as NSString).expandingTildeInPath

func showAlert(message: String, info: String, style: NSAlert.Style = .informational) -> NSApplication.ModalResponse {
    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = info
    alert.alertStyle = style
    return alert.runModal()
}

func showConfirm(message: String, info: String) -> Bool {
    let alert = NSAlert()
    alert.messageText = message
    alert.informativeText = info
    alert.alertStyle = .warning
    alert.addButton(withTitle: "Uninstall")
    alert.addButton(withTitle: "Cancel")
    return alert.runModal() == .alertFirstButtonReturn
}

@discardableResult
func run(_ launchPath: String, _ args: [String]) -> Int32 {
    let task = Process()
    task.launchPath = launchPath
    task.arguments = args
    task.standardOutput = Pipe()
    task.standardError = Pipe()
    do {
        try task.run()
        task.waitUntilExit()
        return task.terminationStatus
    } catch {
        return -1
    }
}

func uninstall() -> (Bool, String) {
    var log: [String] = []

    // 1. Bootout the agent (best-effort — if not loaded, this is a no-op rc=3).
    let uid = getuid()
    let bootoutRC = run("/bin/launchctl", ["bootout", "gui/\(uid)/\(label)"])
    log.append("launchctl bootout: rc=\(bootoutRC) (0=ok, 3=not loaded; both fine)")

    // 2. Remove the LaunchAgent plist.
    if FileManager.default.fileExists(atPath: plistPath) {
        do {
            try FileManager.default.removeItem(atPath: plistPath)
            log.append("removed \(plistPath)")
        } catch {
            log.append("WARN: failed to remove plist: \(error.localizedDescription)")
        }
    } else {
        log.append("plist not present at \(plistPath)")
    }

    // 3. Trampoline-delete the helper directory + this .app.
    //    We write a script to /tmp that waits for us to exit, then
    //    rm -rf's the entire CLI-Pulse-Helper directory (which includes
    //    this very Uninstaller.app), then removes itself.
    let scriptPath = "/tmp/cli-pulse-uninstall-\(getpid()).sh"
    let script = """
    #!/bin/sh
    # CLI Pulse Helper trampoline cleanup script
    # Generated by Uninstaller.app PID \(getpid())
    sleep 1
    rm -rf "\(helperDir)"
    rm -- "$0"
    """
    do {
        try script.write(toFile: scriptPath, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes(
            [.posixPermissions: NSNumber(value: Int16(0o755))],
            ofItemAtPath: scriptPath
        )
        log.append("wrote trampoline at \(scriptPath)")
    } catch {
        return (false, "Failed to write trampoline: \(error.localizedDescription)")
    }

    // Spawn the trampoline DETACHED — nohup-style — so it lives past
    // our exit. /bin/sh -c lets us fully detach via & + disown semantics.
    let detach = Process()
    detach.launchPath = "/bin/sh"
    detach.arguments = ["-c", "nohup \(scriptPath) </dev/null >/dev/null 2>&1 &"]
    do {
        try detach.run()
        // DO NOT waitUntilExit — we want to return immediately so the
        // user clicks OK on the success alert and we exit, allowing the
        // trampoline's `sleep 1` to win the race.
    } catch {
        return (false, "Failed to spawn trampoline: \(error.localizedDescription)")
    }

    log.append("trampoline scheduled — helper directory will be removed after this app exits")
    return (true, log.joined(separator: "\n"))
}

// === Entry point ===

let app = NSApplication.shared
// .accessory: no Dock icon, no menu bar — cleaner UX for a transient utility.
// (Per Gemini review of slice 4E.1.5.)
app.setActivationPolicy(.accessory)
// Ensure modal alerts appear above other windows even without a Dock icon.
NSApp.activate(ignoringOtherApps: true)

let confirm = showConfirm(
    message: "Uninstall CLI Pulse Companion CLI?",
    info: "This will stop the helper, remove the LaunchAgent, and delete \(helperDir). The main CLI Pulse app will remain installed."
)

if !confirm {
    exit(0)
}

let (ok, message) = uninstall()

if ok {
    _ = showAlert(
        message: "Companion CLI Uninstalled",
        info: "The helper has been removed. You can re-install it any time from the CLI Pulse app's Pairing settings."
    )
    exit(0)
} else {
    _ = showAlert(
        message: "Uninstall Failed",
        info: message,
        style: .critical
    )
    exit(1)
}
