-- ============================================================================
-- 20_remote_tables.sql — focused, faithful DDL for the remote-control tables
-- that the RLS denial tests cover but that live in the large feature migrations
-- (migrate_v0.26+), not in schema.sql.
--
-- Columns/types/nullability/defaults and the RLS policies are transcribed from
-- LIVE prod (gkjwsxotmwrgqsvfijzs, verified 2026-06-27 via information_schema +
-- pg_policies) so the denial assertions exercise the REAL policy shapes:
--   remote_sessions            → SELECT own, DELETE own        (no INSERT/UPDATE policy)
--   remote_session_commands    → SELECT own                    (no INSERT/UPDATE/DELETE policy)
--   remote_session_events      → SELECT own                    ( "" )
--   remote_permission_requests → SELECT own                    ( "" )
--   remote_permission_decisions→ SELECT own                    ( "" )
-- All writes happen server-side via SECURITY DEFINER RPCs (helper/app), so the
-- table-level grant to `authenticated` is read-mostly and RLS must deny every
-- cross-user read and every direct client write.
--
-- device_id is intentionally a bare uuid here (prod FKs it to devices(id)); the
-- denial tests must fail on RLS, not on an unrelated FK, so we don't require a
-- seeded device.
-- ============================================================================

create table if not exists public.remote_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id uuid not null,
  provider text not null,
  cwd_basename text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  realtime_private boolean not null default false
);
alter table public.remote_sessions enable row level security;
create policy "Users can read own remote sessions"
  on public.remote_sessions for select using ((select auth.uid()) = user_id);
create policy "Users can delete own remote sessions"
  on public.remote_sessions for delete using ((select auth.uid()) = user_id);

create table if not exists public.remote_session_commands (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id uuid not null,
  kind text not null,
  payload text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);
alter table public.remote_session_commands enable row level security;
create policy "Users can read own commands"
  on public.remote_session_commands for select using ((select auth.uid()) = user_id);

create table if not exists public.remote_session_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id uuid not null,
  seq integer not null,
  kind text not null,
  payload text not null,
  created_at timestamptz not null default now()
);
alter table public.remote_session_events enable row level security;
create policy "Users can read own session events"
  on public.remote_session_events for select using ((select auth.uid()) = user_id);

create table if not exists public.remote_permission_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_id uuid not null,
  provider text not null,
  tool_name text not null default '',
  summary text not null default '',
  payload jsonb not null default '{}'::jsonb,
  risk text not null default 'medium',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '5 minutes'),
  notification_attempts integer not null default 0
);
alter table public.remote_permission_requests enable row level security;
create policy "Users can read own permission requests"
  on public.remote_permission_requests for select using ((select auth.uid()) = user_id);

create table if not exists public.remote_permission_decisions (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  decision text not null,
  scope text not null default 'once',
  created_at timestamptz not null default now()
);
alter table public.remote_permission_decisions enable row level security;
create policy "Users can read own decisions"
  on public.remote_permission_decisions for select using ((select auth.uid()) = user_id);
