// PetGoldenVectorsTests — v1.42 Pulse Cat M1.
//
// Verifies PetEngine against the committed cross-platform contract
// (Resources/PetGoldenVectors.json). The vectors are generated by an INDEPENDENT
// spec oracle committed at `scripts/pet_golden_oracle.py` (a from-scratch Python
// reimplementation of plan §1.2 — NOT the Swift code), so agreement here means
// the Swift engine matches the spec, not merely itself. Regenerate + diff:
//   python3 scripts/pet_golden_oracle.py | diff - "CLI Pulse Bar/CLIPulseCore/Sources/CLIPulseCore/Resources/PetGoldenVectors.json"
// A future Rust port validates against the same JSON.

import XCTest
@testable import CLIPulseCore

final class PetGoldenVectorsTests: XCTestCase {

    func test_golden_vectors_load() throws {
        let file = try XCTUnwrap(PetGoldenVectors.loadBundled(),
                                 "PetGoldenVectors.json must be bundled in the module")
        XCTAssertEqual(file.rulesetVersion, PetRuleset.version)
        XCTAssertEqual(file.weightTableVersion, PetWeightTable.version)
        XCTAssertGreaterThanOrEqual(file.cases.count, 20, "contract requires ≥20 cases")
    }

    func test_engine_matches_every_golden_case() throws {
        let file = try XCTUnwrap(PetGoldenVectors.loadBundled())
        for c in file.cases {
            let d = PetGoldenVectors.evaluate(c)
            let e = c.expect
            XCTAssertEqual(d.profile.qualified, e.qualified, "[\(c.name)] qualified")
            XCTAssertEqual(d.timingAllows, e.timingAllows, "[\(c.name)] timingAllows")
            XCTAssertEqual(d.profile.dominantFamily, e.dominantFamily, "[\(c.name)] dominantFamily")
            XCTAssertEqual(d.profile.tempo.rawValue, e.tempo, "[\(c.name)] tempo")
            XCTAssertEqual(d.profile.resolvedForm.rawValue, e.resolvedForm, "[\(c.name)] resolvedForm")
            XCTAssertEqual(d.shouldHatch, e.shouldHatch, "[\(c.name)] shouldHatch")
            XCTAssertEqual(d.hatchedForm?.rawValue, e.hatchedForm, "[\(c.name)] hatchedForm")
            XCTAssertEqual(d.alreadyOwnedThisWeek, e.alreadyOwned, "[\(c.name)] alreadyOwned")
            XCTAssertEqual(d.eggStage.rawValue, e.eggStage, "[\(c.name)] eggStage")
        }
    }

    /// The contract must cover the load-bearing edges named in the plan.
    func test_golden_vectors_cover_required_edges() throws {
        let names = Set(try XCTUnwrap(PetGoldenVectors.loadBundled()).cases.map(\.name))
        for required in ["owned_form_waits", "unqualified_two_days", "clock_rollback_no_hatch",
                         "dst_spring_forward_loaf", "timing_allows_exactly_7d",
                         "messages_only_not_qualified", "empty_ledger_idle",
                         "dominance_exactly_55_anthropic", "sparse_one_active_day",
                         "steering_mid_week_to_anthropic", "timezone_travel_frozen_keys",
                         "unavailable_low_provider_ignored", "extreme_scale_no_false_dominance"] {
            XCTAssertTrue(names.contains(required), "missing required golden case: \(required)")
        }
    }
}
