#!/bin/bash
# Phase 4D P1.5: reproducible signed-app build.
#
# Codex review on PR #20: the previous Phase 4 / Phase 4D
# instructions asked Jason to manually edit Xcode build phases
# (Run Script + Copy Files), which means a clean checkout cannot
# produce a working app and CI's green build doesn't prove the
# helper is embedded. This script fixes that — a clean checkout
# plus `./scripts/build_signed_app.sh` produces a signed .app with
# the helper binary + LaunchAgent plist in place at the right
# paths.
#
# What it does:
#   1. Build the Swift helper in release mode.
#   2. Build the macOS app via xcodebuild.
#   3. Copy `HelperSwift/.build/release/cli_pulse_helper` into
#      `<App>/Contents/Helpers/cli_pulse_helper`.
#   4. Copy `CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist` into
#      `<App>/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.plist`.
#   5. Codesign the embedded helper binary with the app's signing
#      identity (so SMAppService.register accepts it).
#   6. Re-sign the .app so the additions are part of the
#      signature seal.
#   7. Verify the final bundle structure.
#
# Usage:
#   ./scripts/build_signed_app.sh [Debug|Release] [<output-dir>]
#
# Defaults: configuration=Debug, output-dir=./build_app_output.
#
# CI integration: invoke this script instead of raw xcodebuild.
# A passing CI run proves the helper IS embedded + signed in the
# shipped artifact.
#
# Why this approach instead of pbxproj edits:
#   - pbxproj editing via Ruby `xcodeproj` adds a toolchain
#     dependency CI would have to install.
#   - pbxproj is regenerated by Xcode UI in subtle ways; manual
#     edits create review churn.
#   - The script works identically from CI, from Jason's
#     terminal, and as a post-build step a Run Script phase
#     can shell out to. Single source of truth.

set -euo pipefail

CONFIGURATION="${1:-Debug}"
OUTPUT_DIR="${2:-$PWD/build_app_output}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SWIFT_PKG_DIR="$PROJECT_ROOT/HelperSwift"
APP_PROJECT="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar.xcodeproj"
APP_SCHEME="CLI Pulse Bar"
PLIST_TEMPLATE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist"
DERIVED_DATA="$OUTPUT_DIR/DerivedData"

# 1. Build the Swift helper.
echo "==> [1/7] Building Swift helper (release) ..."
cd "$SWIFT_PKG_DIR"
swift build -c release
HELPER_BIN="$SWIFT_PKG_DIR/.build/release/cli_pulse_helper"
[[ -x "$HELPER_BIN" ]] || { echo "error: helper binary missing at $HELPER_BIN" >&2; exit 1; }
HELPER_SIZE="$(du -h "$HELPER_BIN" | cut -f1)"
echo "    built: $HELPER_BIN ($HELPER_SIZE)"

# 2. Build the macOS app.
echo "==> [2/7] Building CLI Pulse Bar.app ($CONFIGURATION) ..."
cd "$PROJECT_ROOT/CLI Pulse Bar"
xcodebuild \
    -project "$APP_PROJECT" \
    -scheme "$APP_SCHEME" \
    -configuration "$CONFIGURATION" \
    -derivedDataPath "$DERIVED_DATA" \
    build CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO

APP_PATH="$DERIVED_DATA/Build/Products/$CONFIGURATION/CLI Pulse Bar.app"
[[ -d "$APP_PATH" ]] || { echo "error: built .app not found at $APP_PATH" >&2; exit 1; }
echo "    built: $APP_PATH"

# 3. Copy helper binary into Contents/Helpers/.
echo "==> [3/7] Embedding helper at Contents/Helpers/ ..."
mkdir -p "$APP_PATH/Contents/Helpers"
cp "$HELPER_BIN" "$APP_PATH/Contents/Helpers/cli_pulse_helper"
chmod +x "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# 4. Copy LaunchAgent plist into Contents/Library/LaunchAgents/.
echo "==> [4/7] Embedding LaunchAgent plist at Contents/Library/LaunchAgents/ ..."
mkdir -p "$APP_PATH/Contents/Library/LaunchAgents"
cp "$PLIST_TEMPLATE" "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.plist"

# 5. Resolve signing identity (skipped for ad-hoc / Debug builds).
echo "==> [5/7] Resolving signing identity ..."
SIGN_IDENTITY="-"   # ad-hoc by default
if [[ -n "${CODE_SIGN_IDENTITY:-}" ]]; then
    SIGN_IDENTITY="$CODE_SIGN_IDENTITY"
fi

# 6. Sign the helper binary first (must happen BEFORE the app
#    re-sign so the helper is part of the parent's signature
#    closure).
echo "==> [6/7] Codesigning helper + re-signing .app (identity=$SIGN_IDENTITY) ..."
codesign --force --options runtime --timestamp=none \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# Re-sign the app bundle deeply to seal the new files.
codesign --force --deep --options runtime --timestamp=none \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH"

# 7. Verify.
echo "==> [7/7] Verifying bundle ..."
test -x "$APP_PATH/Contents/Helpers/cli_pulse_helper"
test -f "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.plist"
codesign --verify --deep --strict "$APP_PATH"
echo "    OK: $APP_PATH is signed + has helper + has LaunchAgent plist"

echo ""
echo "Final layout:"
echo "  $APP_PATH/Contents/Helpers/cli_pulse_helper                       # Mach-O helper, signed"
echo "  $APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.plist # LaunchAgent plist"
echo ""
echo "Open the .app with Finder to test, or run:"
echo "  open '$APP_PATH'"
