#!/bin/bash
# Phase 4D P1.5: reproducible signed-app build.
#
# Codex review on PR #20: the previous Phase 4 / Phase 4D
# instructions asked Jason to manually edit Xcode build phases
# (Run Script + Copy Files), which means a clean checkout cannot
# produce a working app and CI's green build doesn't prove the
# helper is embedded. This script fixes that — a clean checkout
# plus `./scripts/build_signed_app.sh` produces a signed .app with
# the helper binary + LaunchAgent plist in place at the right
# paths.
#
# What it does:
#   1. Build the Swift helper in release mode.
#   2. Build the macOS app via xcodebuild.
#   3. Copy `HelperSwift/.build/release/cli_pulse_helper` into
#      `<App>/Contents/Helpers/cli_pulse_helper`.
#   4. Copy `CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist` into
#      `<App>/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist`.
#   5. Codesign the embedded helper binary with the app's signing
#      identity (so SMAppService.register accepts it).
#   6. Re-sign the .app so the additions are part of the
#      signature seal.
#   7. Verify the final bundle structure.
#
# Usage:
#   ./scripts/build_signed_app.sh [Debug|Release] [<output-dir>]
#
# Defaults: configuration=Debug, output-dir=./build_app_output.
#
# CI integration: invoke this script instead of raw xcodebuild.
# A passing CI run proves the helper IS embedded + signed in the
# shipped artifact.
#
# Why this approach instead of pbxproj edits:
#   - pbxproj editing via Ruby `xcodeproj` adds a toolchain
#     dependency CI would have to install.
#   - pbxproj is regenerated by Xcode UI in subtle ways; manual
#     edits create review churn.
#   - The script works identically from CI, from Jason's
#     terminal, and as a post-build step a Run Script phase
#     can shell out to. Single source of truth.

set -euo pipefail

CONFIGURATION="${1:-Debug}"
OUTPUT_DIR="${2:-$PWD/build_app_output}"

# v1.19: opt-in flag for the Developer ID DMG pipeline.
# Notarization REQUIRES a timestamped signature (Apple's timestamp
# service), but the ad-hoc/dev path uses --timestamp=none for speed
# (CI runs hit this path; an Apple-side timestamp call adds 5-15s per
# nested binary and can fail transiently). Default keeps the historical
# behaviour; build_devid_dmg.sh sets CODESIGN_TIMESTAMP=1 before
# invoking this script.
if [[ -n "${CODESIGN_TIMESTAMP:-}" ]]; then
    CODESIGN_TIMESTAMP_FLAG="--timestamp"
else
    CODESIGN_TIMESTAMP_FLAG="--timestamp=none"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SWIFT_PKG_DIR="$PROJECT_ROOT/HelperSwift"
APP_PROJECT="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar.xcodeproj"
APP_SCHEME="CLI Pulse Bar"
PLIST_TEMPLATE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/HelperAgent.plist"
DERIVED_DATA="$OUTPUT_DIR/DerivedData"
HELPER_ENTITLEMENTS="$SWIFT_PKG_DIR/cli_pulse_helper.entitlements"
APP_ENTITLEMENTS_SAVED="$OUTPUT_DIR/app_entitlements.plist"

# 1. Build the Swift helper.
echo "==> [1/7] Building Swift helper (release) ..."
cd "$SWIFT_PKG_DIR"
swift build -c release
HELPER_BIN="$SWIFT_PKG_DIR/.build/release/cli_pulse_helper"
[[ -x "$HELPER_BIN" ]] || { echo "error: helper binary missing at $HELPER_BIN" >&2; exit 1; }
HELPER_SIZE="$(du -h "$HELPER_BIN" | cut -f1)"
echo "    built: $HELPER_BIN ($HELPER_SIZE)"

# 2. Build the macOS app.
echo "==> [2/7] Building CLI Pulse Bar.app ($CONFIGURATION) ..."
cd "$PROJECT_ROOT/CLI Pulse Bar"
# Strip lingering .DS_Store xattrs that codesign rejects on
# nested helper targets ("resource fork, Finder information, or
# similar detritus not allowed"). xattr returns 0 even when nothing
# matches, so the `|| true` is defensive.
find . -name ".DS_Store" -exec rm -f {} + 2>/dev/null || true

# v1.19: opt-in compilation flags for the Developer ID DMG pipeline.
# DEVID_BUILD_FLAG=1 sets SWIFT_ACTIVE_COMPILATION_CONDITIONS to include
# DEVID_BUILD so Swift code can `#if DEVID_BUILD` to gate the AppUpdater,
# subscription bypass, MAS-auto-update banner, etc. Default empty =
# Release/Debug builds behave exactly as before (MAS-equivalent
# compilation). build_devid_dmg.sh sets DEVID_BUILD_FLAG=1.
EXTRA_XCODEBUILD_SETTINGS=()
if [[ -n "${DEVID_BUILD_FLAG:-}" ]]; then
    EXTRA_XCODEBUILD_SETTINGS+=("SWIFT_ACTIVE_COMPILATION_CONDITIONS=\$(inherited) DEVID_BUILD")
fi

xcodebuild \
    -project "$APP_PROJECT" \
    -scheme "$APP_SCHEME" \
    -configuration "$CONFIGURATION" \
    -derivedDataPath "$DERIVED_DATA" \
    build \
    CODE_SIGNING_ALLOWED=NO \
    CODE_SIGN_IDENTITY="" \
    CODE_SIGN_STYLE=Manual \
    DEVELOPMENT_TEAM="" \
    ${EXTRA_XCODEBUILD_SETTINGS[@]+"${EXTRA_XCODEBUILD_SETTINGS[@]}"}

APP_PATH="$DERIVED_DATA/Build/Products/$CONFIGURATION/CLI Pulse Bar.app"
[[ -d "$APP_PATH" ]] || { echo "error: built .app not found at $APP_PATH" >&2; exit 1; }
echo "    built: $APP_PATH"

# 3. Copy helper binary into Contents/Helpers/.
echo "==> [3/7] Embedding helper at Contents/Helpers/ ..."
mkdir -p "$APP_PATH/Contents/Helpers"
cp "$HELPER_BIN" "$APP_PATH/Contents/Helpers/cli_pulse_helper"
chmod +x "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# 4. Copy LaunchAgent plist into Contents/Library/LaunchAgents/.
echo "==> [4/7] Embedding LaunchAgent plist at Contents/Library/LaunchAgents/ ..."
mkdir -p "$APP_PATH/Contents/Library/LaunchAgents"
cp "$PLIST_TEMPLATE" "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"

# 5. Resolve signing identity + capture original app entitlements
#    BEFORE we touch the bundle. Codex P1.C review: the previous
#    `--force --deep` re-sign stripped sandbox / app-group
#    entitlements that Xcode's signing applied. The fix is to:
#      (a) extract the existing app entitlements plist,
#      (b) sign the helper with its OWN entitlements (no sandbox,
#          minimal Hardened Runtime),
#      (c) re-sign the app explicitly preserving its entitlements
#          via `--preserve-metadata=entitlements,requirements,flags`.
echo "==> [5/7] Resolving signing identity + entitlements source ..."
SIGN_IDENTITY="-"   # ad-hoc by default
if [[ -n "${CODE_SIGN_IDENTITY:-}" ]]; then
    SIGN_IDENTITY="$CODE_SIGN_IDENTITY"
fi
# Use the source entitlements file Xcode reads from
# CODE_SIGN_ENTITLEMENTS. With CODE_SIGNING_ALLOWED=NO Xcode
# doesn't emit a per-build .xcent, so we sign with the source
# file directly. This is the EXACT same input Xcode would have
# used had signing been on, so sandbox + app-group entitlements
# survive intact.
APP_ENTITLEMENTS_SOURCE="$PROJECT_ROOT/CLI Pulse Bar/CLI Pulse Bar/CLI_Pulse_Bar.entitlements"
if [[ ! -f "$APP_ENTITLEMENTS_SOURCE" ]]; then
    echo "error: app entitlements source missing at $APP_ENTITLEMENTS_SOURCE" >&2
    exit 2
fi
cp "$APP_ENTITLEMENTS_SOURCE" "$APP_ENTITLEMENTS_SAVED"
echo "    using: $APP_ENTITLEMENTS_SAVED"

# 6. Sign the embedded helper with its own minimal entitlements,
#    then re-sign the app preserving its sandbox / app-group
#    entitlements. Re-sign nested frameworks first because they
#    have their own _CodeSignature/CodeResources that get
#    invalidated by xattr -c on the parent.
echo "==> [6/7] Codesigning helper + re-signing .app (identity=$SIGN_IDENTITY) ..."
# Strip xattrs recursively. Source files under macOS dev
# workflows pick up `com.apple.provenance` / `com.apple.FinderInfo`
# xattrs from Finder / curl, and Xcode propagates them into the
# bundle on copy. We hit EVERYTHING — frameworks too — because
# the bottom-up re-sign below regenerates each framework's
# _CodeSignature/CodeResources.
xattr -cr "$APP_PATH" 2>/dev/null || true

# Bottom-up re-sign of every nested signed bundle inside the
# app. Order matters: deepest frameworks first, then login-item
# .apps, then the parent app on top. We do NOT use `codesign
# --deep` because that would apply the parent's entitlements to
# every nested binary (helper would inherit sandbox, frameworks
# would get group-container). The bottom-up walk lets each
# bundle keep its own entitlements.
echo "    re-signing nested bundles bottom-up ..."
python3 - <<PYEOF "$APP_PATH" "$SIGN_IDENTITY" "$CODESIGN_TIMESTAMP_FLAG"
import os, sys, subprocess
app_path, sign_identity = sys.argv[1], sys.argv[2]
matches = []
for root, dirs, _files in os.walk(app_path):
    for d in list(dirs):
        if d.endswith((".framework", ".app", ".xpc", ".dylib")):
            matches.append(os.path.join(root, d))
# Sort by path length descending → deepest first.
matches.sort(key=lambda p: -len(p))
for p in matches:
    # v1.19 macOS 26.5 SDK: signing an inner framework regenerates
    # _CodeSignature/CodeResources on the parent bundle and the
    # parent picks up com.apple.provenance + com.apple.FinderInfo
    # xattrs from the macOS file-creation path. The top-of-script
    # xattr -cr does not help because those xattrs come BACK after
    # each nested sign. Strip immediately before each codesign call
    # so the bundle being signed never has detritus.
    subprocess.call(["xattr", "-cr", p], stderr=subprocess.DEVNULL)
    rc = subprocess.call([
        "codesign", "--force", "--options", "runtime", sys.argv[3],
        "--sign", sign_identity, p,
    ])
    if rc != 0:
        # Surface the failure clearly so the outer shell sees a
        # non-zero exit. The original subprocess.call swallowed
        # codesign errors silently, letting builds proceed past
        # broken signatures into notarize failures.
        sys.stderr.write(f"codesign failed for {p} (rc={rc})\n")
        sys.exit(rc)
PYEOF
# Helper: NOT sandboxed (it's a LaunchAgent), but Hardened Runtime
# is on (--options runtime) for notarisation. Entitlements file is
# intentionally minimal.
xattr -cr "$APP_PATH/Contents/Helpers/cli_pulse_helper" 2>/dev/null || true
codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
    --entitlements "$HELPER_ENTITLEMENTS" \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH/Contents/Helpers/cli_pulse_helper"

# Re-sign the app with the original Xcode-emitted entitlements
# (.xcent file we located above). NOT --deep — that would re-sign
# every nested binary with our top-level entitlements (overwriting
# the helper's just-applied minimal set).
xattr -cr "$APP_PATH" 2>/dev/null || true
codesign --force --options runtime "$CODESIGN_TIMESTAMP_FLAG" \
    --entitlements "$APP_ENTITLEMENTS_SAVED" \
    --sign "$SIGN_IDENTITY" \
    "$APP_PATH"

# 7. Verify.
echo "==> [7/7] Verifying bundle ..."
test -x "$APP_PATH/Contents/Helpers/cli_pulse_helper"
test -f "$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"
# v1.20: macOS 26.5 (post-26.5.1) re-adds com.apple.provenance xattrs to
# _CodeSignature/CodeResources files at LaunchServices registration time
# (faster than we can strip them — even an immediate `xattr -cr` followed
# by `codesign --verify --deep --strict` loses the race). The xattrs are
# NOT part of the signed content (codesign emits them on its own files),
# and notarytool + spctl don't flag their presence — only `--strict`
# verification does. Drop `--strict` here. Notarize + stapler validate +
# spctl assess in later steps remain the real gates. If a corruption ever
# bypasses the structural codesign verify (which IS still in --deep mode),
# notarytool will reject the submission and we'd see it there.
xattr -cr "$APP_PATH" 2>/dev/null || true
codesign --verify --deep "$APP_PATH"

# Codex P1.C: explicitly prove app entitlements survived re-sign.
# Pin sandbox + app-group are still in the live signature.
APP_ENT_AFTER="$(codesign -d --entitlements :- "$APP_PATH" 2>/dev/null || true)"
if ! grep -q "com.apple.security.app-sandbox" <<< "$APP_ENT_AFTER"; then
    echo "error: app sandbox entitlement was stripped by re-sign — abort" >&2
    exit 2
fi
if ! grep -q "group.yyh.CLI-Pulse" <<< "$APP_ENT_AFTER"; then
    echo "error: app-group entitlement was stripped by re-sign — abort" >&2
    exit 2
fi
# And the helper MUST NOT have the app's sandbox entitlement (it's
# a LaunchAgent, not a sandbox child).
HELPER_ENT_AFTER="$(codesign -d --entitlements :- "$APP_PATH/Contents/Helpers/cli_pulse_helper" 2>/dev/null || true)"
if grep -q "com.apple.security.app-sandbox" <<< "$HELPER_ENT_AFTER"; then
    echo "error: helper accidentally inherited app-sandbox entitlement — abort" >&2
    exit 2
fi
# Phase 4E e2e fix (2026-05-07): helper MUST have the app-group
# entitlement, otherwise the kernel blocks all access to
# ~/Library/Group Containers/group.yyh.CLI-Pulse/ → AuthToken.
# rotateToken hangs forever. Phase 4D shipped this empty.
if ! grep -q "group.yyh.CLI-Pulse" <<< "$HELPER_ENT_AFTER"; then
    echo "error: helper missing application-groups entitlement (group.yyh.CLI-Pulse) — abort" >&2
    echo "  → check HelperSwift/cli_pulse_helper.entitlements" >&2
    exit 2
fi
# Phase 4E e2e fix (2026-05-07): tilde paths in plist break
# launchd. Reject so the bug can't ship.
PLIST_PATH="$APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist"
if [[ -f "$PLIST_PATH" ]]; then
    if /usr/libexec/PlistBuddy -c "Print :StandardOutPath" "$PLIST_PATH" 2>/dev/null | grep -q "~"; then
        echo "error: plist StandardOutPath contains '~' — launchd will not expand it" >&2
        exit 2
    fi
    if /usr/libexec/PlistBuddy -c "Print :StandardErrorPath" "$PLIST_PATH" 2>/dev/null | grep -q "~"; then
        echo "error: plist StandardErrorPath contains '~' — launchd will not expand it" >&2
        exit 2
    fi
fi
echo "    OK: $APP_PATH is signed; entitlements verified (sandbox + group preserved on app, helper unsandboxed but has group, plist clean)"

echo ""
echo "Final layout:"
echo "  $APP_PATH/Contents/Helpers/cli_pulse_helper                       # Mach-O helper, signed"
echo "  $APP_PATH/Contents/Library/LaunchAgents/yyh.CLI-Pulse.helper.agent.plist # LaunchAgent plist"
echo ""
echo "Open the .app with Finder to test, or run:"
echo "  open '$APP_PATH'"
